DROP HTTP [host=*.org] [user-agent=regex:^curl.*]

DROP HTTP [host=*.ru]

DROP HTTP [uri=regex:.*\.exe$]

DROP HTTP [method=POST] [host=example.com]

ACCEPT HTTP [host=internal.service.local] [user-agent=MyMonitoringBot/1.0]

DROP HTTP [host=internal.service.local]

ACCEPT ALL